class Autogenerated {
  Id iId;
  Images images;
  List<String> description;
  List<Metadata> metadata;
  String binding;
  String brand;
  Catalognumberlist catalognumberlist;
  String ean;
  String esrbagerating;
  List<String> feature;
  String format;
  String genre;
  String hardwareplatform;
  String label;
  int price;
  String currency;
  String manufacturer;
  String model;
  String mpn;
  int numberofitems;
  String operatingsystem;
  String packagequantity;
  String partnumber;
  List<String> platform;
  String productgroup;
  String producttypename;
  String publisher;
  Releasedate releasedate;
  String studio;
  String title;
  String upc;
  Upclist upclist;
  String category;
  int salesrank;

  Autogenerated(
      {this.iId,
      this.images,
      this.description,
      this.metadata,
      this.binding,
      this.brand,
      this.catalognumberlist,
      this.ean,
      this.esrbagerating,
      this.feature,
      this.format,
      this.genre,
      this.hardwareplatform,
      this.label,
      this.price,
      this.currency,
      this.manufacturer,
      this.model,
      this.mpn,
      this.numberofitems,
      this.operatingsystem,
      this.packagequantity,
      this.partnumber,
      this.platform,
      this.productgroup,
      this.producttypename,
      this.publisher,
      this.releasedate,
      this.studio,
      this.title,
      this.upc,
      this.upclist,
      this.category,
      this.salesrank});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    iId = json['_id'] != null ? new Id.fromJson(json['_id']) : null;
    images =
        json['images'] != null ? new Images.fromJson(json['images']) : null;
    description = json['description'].cast<String>();
    if (json['metadata'] != null) {
      metadata = new List<Metadata>();
      json['metadata'].forEach((v) {
        metadata.add(new Metadata.fromJson(v));
      });
    }
    binding = json['binding'];
    brand = json['brand'];
    catalognumberlist = json['catalognumberlist'] != null
        ? new Catalognumberlist.fromJson(json['catalognumberlist'])
        : null;
    ean = json['ean'];
    esrbagerating = json['esrbagerating'];
    feature = json['feature'].cast<String>();
    format = json['format'];
    genre = json['genre'];
    hardwareplatform = json['hardwareplatform'];
    label = json['label'];
    price = json['price'];
    currency = json['currency'];
    manufacturer = json['manufacturer'];
    model = json['model'];
    mpn = json['mpn'];
    numberofitems = json['numberofitems'];
    operatingsystem = json['operatingsystem'];
    packagequantity = json['packagequantity'];
    partnumber = json['partnumber'];
    platform = json['platform'].cast<String>();
    productgroup = json['productgroup'];
    producttypename = json['producttypename'];
    publisher = json['publisher'];
    releasedate = json['releasedate'] != null
        ? new Releasedate.fromJson(json['releasedate'])
        : null;
    studio = json['studio'];
    title = json['title'];
    upc = json['upc'];
    upclist =
        json['upclist'] != null ? new Upclist.fromJson(json['upclist']) : null;
    category = json['category'];
    salesrank = json['salesrank'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.iId != null) {
      data['_id'] = this.iId.toJson();
    }
    if (this.images != null) {
      data['images'] = this.images.toJson();
    }
    data['description'] = this.description;
    if (this.metadata != null) {
      data['metadata'] = this.metadata.map((v) => v.toJson()).toList();
    }
    data['binding'] = this.binding;
    data['brand'] = this.brand;
    if (this.catalognumberlist != null) {
      data['catalognumberlist'] = this.catalognumberlist.toJson();
    }
    data['ean'] = this.ean;
    data['esrbagerating'] = this.esrbagerating;
    data['feature'] = this.feature;
    data['format'] = this.format;
    data['genre'] = this.genre;
    data['hardwareplatform'] = this.hardwareplatform;
    data['label'] = this.label;
    data['price'] = this.price;
    data['currency'] = this.currency;
    data['manufacturer'] = this.manufacturer;
    data['model'] = this.model;
    data['mpn'] = this.mpn;
    data['numberofitems'] = this.numberofitems;
    data['operatingsystem'] = this.operatingsystem;
    data['packagequantity'] = this.packagequantity;
    data['partnumber'] = this.partnumber;
    data['platform'] = this.platform;
    data['productgroup'] = this.productgroup;
    data['producttypename'] = this.producttypename;
    data['publisher'] = this.publisher;
    if (this.releasedate != null) {
      data['releasedate'] = this.releasedate.toJson();
    }
    data['studio'] = this.studio;
    data['title'] = this.title;
    data['upc'] = this.upc;
    if (this.upclist != null) {
      data['upclist'] = this.upclist.toJson();
    }
    data['category'] = this.category;
    data['salesrank'] = this.salesrank;
    return data;
  }
}

class Id {
  String oid;

  Id({this.oid});

  Id.fromJson(Map<String, dynamic> json) {
    oid = json['$oid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$oid'] = this.oid;
    return data;
  }
}

class Images {
  Small small;
  Small medium;
  Small large;

  Images({this.small, this.medium, this.large});

  Images.fromJson(Map<String, dynamic> json) {
    small = json['small'] != null ? new Small.fromJson(json['small']) : null;
    medium = json['medium'] != null ? new Small.fromJson(json['medium']) : null;
    large = json['large'] != null ? new Small.fromJson(json['large']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.small != null) {
      data['small'] = this.small.toJson();
    }
    if (this.medium != null) {
      data['medium'] = this.medium.toJson();
    }
    if (this.large != null) {
      data['large'] = this.large.toJson();
    }
    return data;
  }
}

class Small {
  String url;
  String width;
  String height;

  Small({this.url, this.width, this.height});

  Small.fromJson(Map<String, dynamic> json) {
    url = json['url'];
    width = json['width'];
    height = json['height'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['url'] = this.url;
    data['width'] = this.width;
    data['height'] = this.height;
    return data;
  }
}

class Metadata {
  String key;
  String value;

  Metadata({this.key, this.value});

  Metadata.fromJson(Map<String, dynamic> json) {
    key = json['key'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['key'] = this.key;
    data['value'] = this.value;
    return data;
  }
}

class Catalognumberlist {
  List<String> catalogNumberListElement;

  Catalognumberlist({this.catalogNumberListElement});

  Catalognumberlist.fromJson(Map<String, dynamic> json) {
    catalogNumberListElement = json['CatalogNumberListElement'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['CatalogNumberListElement'] = this.catalogNumberListElement;
    return data;
  }
}

class Releasedate {
  String date;

  Releasedate({this.date});

  Releasedate.fromJson(Map<String, dynamic> json) {
    date = json['$date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$date'] = this.date;
    return data;
  }
}

class Upclist {
  List<String> uPCListElement;

  Upclist({this.uPCListElement});

  Upclist.fromJson(Map<String, dynamic> json) {
    uPCListElement = json['UPCListElement'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['UPCListElement'] = this.uPCListElement;
    return data;
  }
}
